start_urls:
  - "https://news.ycombinator.com"
  - "https://arxiv.org"
max_depth: 2
concurrency: 2
user_agent: "Mozilla/5.0 (X11; Linux x86_64) CoineyScraper/1.0"
headless: true
# proxy: { server: "http://host:port", username: "user", password: "pass" }
output:
  jsonl: "./exports/dataset.jsonl"
  sqlite: "./exports/dataset.db"
  snapshots_dir: "./exports/snapshots"
crawl:
  follow_external: false
  respect_robots: true
  wait_after_load: 1.0
  intercept_api: true
  max_retries: 2
  backoff_base: 0.75
  allow_domains: []
  deny_domains: []
  deny_extensions: [".jpg", ".jpeg", ".png", ".gif", ".svg", ".webp", ".ico", ".pdf", ".zip", ".gz", ".tar", ".rar", ".7z", ".mp3", ".mp4"]
  save_html_snapshot: false
  save_screenshot: false
rate_limit:
  delay_seconds: 0.5
  per_domain_delay_seconds: 0.0
  per_domain_concurrency: 0
github:
  token: ""                # optional, recommended for higher rate limits
  query: "language:python machine learning"
  per_page: 10
  pages: 2
  max_files_per_repo: 200
  extensions: [".py", ".js", ".cpp", ".c", ".java", ".rs"]
  max_file_size: 200000   # bytes
  concurrency: 8
  output_dir: "exports/github_code"
